{
 "title": "asdfsafa231423413",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nginx_parse_errors_total, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(nginx_parse_errors_total{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{instance=\"$node\",job=\"$job\"}[1m]))",
     "legendFormat": "rps trend"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{instance=\"$node\",job=\"$job\"}[1m] offset 1d))",
     "legendFormat": "rps past day"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{instance=\"$node\",job=\"$job\"}[1m] offset 1w))",
     "legendFormat": "rps past week"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(nginx_http_response_count_total{status=~\"2..|3..\", instance=\"$node\"}[1m])) / sum(rate(nginx_http_response_count_total{instance=\"$node\"}[1m]))) * 100",
     "legendFormat": "success rate"
    },
    {
     "expr": "(sum(rate(nginx_http_response_count_total{status=~\"400|401|402|403|404\", instance=\"$node\",job=\"$job\"}[1m])) / sum(rate(nginx_http_response_count_total{instance=\"$node\",job=\"$job\"}[1m]))) * 100",
     "legendFormat": "400-404 rate"
    },
    {
     "expr": "(sum(rate(nginx_http_response_count_total{status=~\"4..\", instance=\"$node\",job=\"$job\"}[1m])) / sum(rate(nginx_http_response_count_total{instance=\"$node\",job=\"$job\"}[1m]))) * 100",
     "legendFormat": "4xx rate"
    },
    {
     "expr": "(sum(rate(nginx_http_response_count_total{status=~\"5..\", instance=\"$node\",job=\"$job\"}[1m])) / sum(rate(nginx_http_response_count_total{instance=\"$node\",job=\"$job\"}[1m]))) * 100",
     "legendFormat": "5xx rate"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"2..\", instance=\"$node\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"3..\", instance=\"$node\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"4..\", instance=\"$node\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"5..\", instance=\"$node\"}[1m])) ",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, request_uri)(rate(nginx_http_response_time_seconds_hist_sum{instance=\"$node\"}[1m])) \n/ \nsum by (method, request_uri)(rate(nginx_http_response_time_seconds_hist_count{instance=\"$node\"}[1m]))",
     "legendFormat": "{{method}}-{{request_uri}}"
    }
   ]
  }
 ]
}