name: ci-cd-test
run-name: executor = ${{ github.actor }}
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up jdk 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: (gradle) cache package
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: build
        run: ./gradlew build

      - name: run test
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up jdk 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: deployment app
        run: |
          echo "deploying app"
          scp -o StrictHostKeyChecking=no build/libs/myapp.jar ssafy@70.12.247.100:/c/noah
          ssh -o StrictHostKeyChecking=no ssafy@70.12.247.100 "java -jar /c/noah/myapp.jar"
